"""CI guard (CLN2): frontend/src/data/categories.generated.json stays in sync
with registry.CATEGORY_DISPLAY.

The JSON is auto-generated by scripts/generate_categories_json.py from the single
source of truth (CATEGORY_DISPLAY). Hand-edits to the JSON — or adding a category
to the registry without regenerating — must fail CI, with a clear fix message,
rather than letting the frontend category list drift.

To fix a failure:

    python scripts/generate_categories_json.py
    git add frontend/src/data/categories.generated.json
    git commit -m "regenerate categories.generated.json"

Spec: docs/pending/2026-08-08_debt-cleanup-batch.md#CLN2
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = PROJECT_ROOT / "scripts" / "generate_categories_json.py"
JSON_PATH = PROJECT_ROOT / "frontend" / "src" / "data" / "categories.generated.json"


def test_categories_json_matches_registry():
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        capture_output=True, text=True, cwd=str(PROJECT_ROOT),
    )
    assert result.returncode == 0, (
        "categories.generated.json is out of sync with registry.CATEGORY_DISPLAY.\n"
        "Fix: run `python scripts/generate_categories_json.py` and commit.\n\n"
        f"{result.stderr}"
    )


def test_categories_json_shape_and_keys():
    """The generated JSON is a list of {key,label} covering every display key."""
    from api.crawler.checkers.registry import CATEGORY_DISPLAY

    data = json.loads(JSON_PATH.read_text())
    assert [(d["key"], d["label"]) for d in data] == list(CATEGORY_DISPLAY)
