"""CI guard: docs/issue-codes.md stays in sync with the catalogue (v2.3 Cycle B).

The doc is auto-generated by ``scripts/generate_issue_codes_doc.py`` from
``_CATALOGUE``, ``_ISSUE_SCORING``, and ``_AI_READINESS_CONFIDENCE``. Hand-edits
to issue-codes.md will be silently lost the next time the generator runs.

This test runs the generator and asserts the output matches the committed file.
A failing build with a clear "re-run the generator" message is much friendlier
than letting drift accumulate.

To fix a failure:

    python scripts/generate_issue_codes_doc.py
    git add docs/issue-codes.md
    git commit -m "regenerate issue-codes.md from catalogue"
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = PROJECT_ROOT / "scripts" / "generate_issue_codes_doc.py"
DOC_PATH = PROJECT_ROOT / "docs" / "issue-codes.md"


def test_issue_codes_doc_matches_catalogue():
    """docs/issue-codes.md must be exactly what the generator produces.

    If this fails, run `python scripts/generate_issue_codes_doc.py` and
    commit the updated doc. Don't edit docs/issue-codes.md by hand — it's
    auto-generated.
    """
    assert SCRIPT.exists(), f"Generator script missing: {SCRIPT}"
    assert DOC_PATH.exists(), (
        f"docs/issue-codes.md missing — run "
        f"`python scripts/generate_issue_codes_doc.py` to create it."
    )

    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
    )
    assert result.returncode == 0, (
        "docs/issue-codes.md is out of sync with the issue catalogue.\n"
        "Fix: run `python scripts/generate_issue_codes_doc.py` and commit the result.\n\n"
        f"Generator stderr:\n{result.stderr}"
    )


def test_generator_script_is_executable():
    """Sanity check the script's shebang and stdout mode work."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--stdout"],
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
    )
    assert result.returncode == 0, (
        f"Generator --stdout failed:\n{result.stderr}"
    )
    # Sanity: stdout contains the auto-generated marker
    assert "auto_generated: true" in result.stdout
    assert "issue codes" in result.stdout.lower()
