"""
Async crawl engine for the TalkingToad crawler.

Orchestrates the full crawl: URL queue management, robots.txt enforcement,
crawl delay, external link checking, and issue aggregation (spec §2.4, §2.8).
"""

import asyncio
import inspect
import logging
import os
from collections import deque
from dataclasses import dataclass, field
from typing import Callable
from urllib.parse import urlparse

import httpx

from api.crawler.fetcher import FetchResult, fetch_page, make_client
from api.crawler.issue_checker import (
    Issue,
    check_amphtml_links,
    check_asset,
    check_cross_page,
    check_page,
    check_url_structure,
    issue_for_status,
    issues_for_redirect,
    make_issue,
)
from api.crawler.normaliser import (
    QueryVariantTracker,
    is_admin_path,
    is_same_domain,
    is_wp_noise_path,
    normalise_url,
)
from api.crawler.parser import ParsedPage, parse_page
from api.crawler.robots import RobotsData, fetch_robots
from api.crawler.sitemap import fetch_sitemap_recursive
from api.models.image import ImageInfo
from api.crawler.image_analyzer import analyze_batch as analyze_images

logger = logging.getLogger(__name__)

_DEFAULT_MAX_PAGES = int(os.getenv("MAX_PAGES_PER_CRAWL", "500"))
_MIN_CRAWL_DELAY_MS = 200
_EXTERNAL_LINK_CAP_PER_PAGE = 50
_EXTERNAL_LINK_CAP_PER_JOB = 500

# Social media and other platforms known to block automated HTTP requests.
# Checking these produces false positives (e.g. LinkedIn returns 999, Facebook
# redirects to a login wall). We skip external link checking for these domains
# entirely — a human click will work fine even though a bot request fails.
_BOT_BLOCKING_DOMAINS: frozenset[str] = frozenset(
    [
        "linkedin.com",
        "www.linkedin.com",
        "facebook.com",
        "www.facebook.com",
        "fb.com",
        "instagram.com",
        "www.instagram.com",
        "twitter.com",
        "www.twitter.com",
        "x.com",
        "www.x.com",
        "tiktok.com",
        "www.tiktok.com",
    ]
)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

# Maps analysis toggle names (v1.3 §3.1) to the issue categories they cover.
_ANALYSIS_CATEGORY_MAP: dict[str, frozenset[str]] = {
    "link_integrity": frozenset({"broken_link", "redirect"}),
    "seo_essentials": frozenset({"metadata", "duplicate", "url_structure"}),
    "site_structure": frozenset({"heading"}),
    "indexability":   frozenset({"crawlability", "sitemap"}),
    "ai_readiness":   frozenset({"ai_readiness"}),
}
# Categories not covered by a named group are always emitted (security).
_UNGROUPED_CATEGORIES: frozenset[str] = frozenset({"security"})


def _enabled_categories(enabled_analyses: list[str] | None) -> frozenset[str] | None:
    """Return the set of allowed issue categories, or None if all are enabled."""
    if enabled_analyses is None:
        return None
    cats: set[str] = set(_UNGROUPED_CATEGORIES)
    for group in enabled_analyses:
        cats.update(_ANALYSIS_CATEGORY_MAP.get(group, frozenset()))
    return frozenset(cats)


@dataclass
class CrawlSettings:
    max_pages: int = _DEFAULT_MAX_PAGES
    crawl_delay_ms: int = 500
    respect_robots: bool = True
    include_subdomains: list[str] = field(default_factory=list)
    # None = all analyses enabled; supply a list of group names to restrict.
    enabled_analyses: list[str] | None = None
    # Image size threshold in KB — images larger than this are flagged as IMG_OVERSIZED.
    img_size_limit_kb: int = 200
    # Page HTML size threshold in KB — pages larger than this are flagged as PAGE_SIZE_LARGE.
    page_size_limit_kb: int = 300
    # Skip WordPress author/category/tag archive pages (default True).
    # These pages are auto-generated by WP and produce non-actionable issues.
    skip_wp_archives: bool = True
    # URLs that the user has manually verified as good — suppress EXTERNAL_LINK_SKIPPED for these.
    verified_link_urls: set[str] = field(default_factory=set)
    # H1 strings to ignore during heading checks — for theme-injected headings that
    # repeat on every page (e.g. a Salient/Avada page-header banner title).
    suppress_h1_strings: list[str] = field(default_factory=list)
    # When True, auto-detect and ignore H1s that don't match the page title.
    suppress_banner_h1: bool = False
    # Href URLs exempt from LINK_EMPTY_ANCHOR — for icon links (social media etc.)
    # that intentionally have no anchor text.
    exempt_anchor_urls: set[str] = field(default_factory=set)


@dataclass
class CrawlResult:
    job_id: str
    pages: list[ParsedPage]
    issues: list[Issue]
    pages_crawled: int
    external_links_checked: int
    cancelled: bool = False
    # (target_url, source_url, link_text) for every broken external link found.
    # Stored so the router can persist them to the links table for the Fix panel.
    broken_link_sources: list[tuple[str, str, str | None]] = field(default_factory=list)
    # v1.9image: Analyzed images with scores and issues
    images: list[ImageInfo] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Engine entry point
# ---------------------------------------------------------------------------

ProgressCallback = Callable[[dict], None]


async def run_crawl(
    job_id: str,
    target_url: str,
    settings: CrawlSettings | None = None,
    *,
    on_progress: ProgressCallback | None = None,
    cancel_event: asyncio.Event | None = None,
) -> CrawlResult:
    """Run a full crawl of *target_url* and return a :class:`CrawlResult`.

    Args:
        job_id: Unique identifier for this crawl job (used in log entries).
        target_url: The start URL to crawl (must include scheme).
        settings: Crawl configuration. Falls back to defaults if None.
        on_progress: Optional callback invoked after each page is crawled.
            Receives a dict with ``pages_crawled``, ``pages_total``, ``current_url``.
        cancel_event: If set, the engine checks this after each page and stops
            cleanly when the event fires.
    """
    print(f"[CRAWL] run_crawl started for {target_url}")
    if settings is None:
        settings = CrawlSettings()

    crawl_delay_s = max(_MIN_CRAWL_DELAY_MS, settings.crawl_delay_ms) / 1000.0

    try:
        normalised_start = normalise_url(target_url)
    except ValueError:
        logger.error("invalid_target_url", extra={"job_id": job_id, "url": target_url})
        return CrawlResult(job_id=job_id, pages=[], issues=[], pages_crawled=0, external_links_checked=0)

    log = logging.LoggerAdapter(logger, {"job_id": job_id})

    async with make_client() as client:
        # ── 1. Fetch robots.txt ────────────────────────────────────────────
        robots_data: RobotsData | None = None
        if settings.respect_robots:
            robots_data = await fetch_robots(normalised_start, client)
            crawl_delay_s = _effective_delay(crawl_delay_s, robots_data)

        # ── 2. Fetch sitemap ──────────────────────────────────────────────
        robots_sitemap_urls = robots_data.sitemap_urls if robots_data else []
        sitemap_result = await fetch_sitemap_recursive(
            normalised_start, client, robots_sitemap_urls=robots_sitemap_urls
        )

        sitemap_url_set: set[str] = set()
        for _su in sitemap_result.urls:
            try:
                sitemap_url_set.add(normalise_url(_su))
            except ValueError:
                sitemap_url_set.add(_su)
        pages_total: int | None = len(sitemap_url_set) if sitemap_url_set else None

        all_pages: list[ParsedPage] = []
        all_issues: list[Issue] = []
        favicon_emitted = False
        hsts_checked_hosts: set[str] = set()

        # ── 2.5. HTTPS redirect check ─────────────────────────────────────
        # If the site is HTTPS, verify that the HTTP version redirects to HTTPS.
        if normalised_start.startswith("https://"):
            http_url = "http://" + normalised_start[8:]
            try:
                http_result = await fetch_page(http_url, client)
                redirects_to_https = (
                    http_result.final_url is not None
                    and http_result.final_url.startswith("https://")
                )
                if not redirects_to_https:
                    all_issues.append(make_issue("HTTPS_REDIRECT_MISSING", normalised_start))
            except Exception:
                pass  # network error — cannot determine redirect behaviour

        # ── 2.6. llms.txt check ───────────────────────────────────────────
        # Check for /llms.txt and /llms-full.txt at the root (spec §2.1).
        parsed_root = urlparse(normalised_start)
        root_url = f"{parsed_root.scheme}://{parsed_root.netloc}"
        try:
            llms_txt_url = f"{root_url}/llms.txt"
            llms_res = await fetch_page(llms_txt_url, client)
            if llms_res.status_code != 200:
                all_issues.append(make_issue("LLMS_TXT_MISSING", normalised_start))
            else:
                # Validation Logic:
                # MIME Type: Must be text/plain.
                # Structure: Verify presence of an H1 title (#), a blockquote summary (>), and a list of key URLs.
                # Efficiency: Flag if the file contains >20 URLs.
                content_type = llms_res.headers.get("content-type", "").lower()
                if "text/plain" not in content_type:
                    issue = make_issue("LLMS_TXT_INVALID", normalised_start)
                    issue.description = f"/llms.txt must have MIME type text/plain (got {content_type})"
                    all_issues.append(issue)
                
                body = llms_res.html or ""
                has_h1 = "# " in body
                has_blockquote = "\n> " in body or body.startswith("> ")
                urls = re.findall(r"https?://\S+", body)
                
                if not has_h1 or not has_blockquote or not urls:
                    issue = make_issue("LLMS_TXT_INVALID", normalised_start)
                    issue.description = "/llms.txt structure is invalid. Must include H1 (#), blockquote summary (>), and URLs."
                    all_issues.append(issue)
                elif len(urls) > 20:
                    issue = make_issue("LLMS_TXT_INVALID", normalised_start)
                    issue.description = "/llms.txt contains > 20 URLs. AI cheat sheets should be curated for 10–20 high-value links."
                    all_issues.append(issue)
        except Exception:
            pass

        # If no sitemap found, record that as an issue
        if sitemap_result.missing_issue:
            all_issues.append(
                Issue(
                    code="SITEMAP_MISSING",
                    category="sitemap",
                    severity="info",
                    description=sitemap_result.missing_issue["message"],
                    recommendation="Create an XML sitemap and submit it to Google Search Console. Most CMS platforms can generate one automatically.",
                    page_url=None,
                )
            )

        # ── 3. Crawl queue setup ──────────────────────────────────────────
        # Queue entries are (url, depth); homepage depth = 0, sitemap-seeded = None
        queue: deque[tuple[str, int | None]] = deque([(normalised_start, 0)])
        visited: set[str] = set()
        variant_tracker = QueryVariantTracker()
        depth_map: dict[str, int | None] = {normalised_start: 0}

        # Seed from sitemap so pages not reachable via HTML links are crawled
        for norm in sitemap_url_set:
            if norm != normalised_start and is_same_domain(norm, normalised_start):
                queue.append((norm, None))
                if norm not in depth_map:
                    depth_map[norm] = None

        # External links: collected during internal crawl, checked after
        # Format: {"source_url": str, "target_url": str, "link_text": str|None}
        external_link_queue: list[dict] = []
        external_per_page_count: dict[str, int] = {}
        external_targets_seen: set[str] = set()  # deduplicate by target URL

        # Image data: collected during internal crawl, analyzed after
        # Format: dict from parser with url, page_url, alt, srcset, etc.
        _IMAGE_URL_CAP_PER_JOB = 150
        image_data_queue: list[dict] = []
        image_targets_seen: set[str] = set()

        # ── 4. Internal crawl loop ────────────────────────────────────────
        while queue:
            if cancel_event and cancel_event.is_set():
                log.info("crawl_cancelled")
                return CrawlResult(
                    job_id=job_id,
                    pages=all_pages,
                    issues=all_issues,
                    pages_crawled=len(all_pages),
                    external_links_checked=0,
                    cancelled=True,
                )

            url, current_depth = queue.popleft()

            if url in visited:
                continue
            visited.add(url)

            if not variant_tracker.record(url):
                log.warning("query_variant_cap_reached", extra={"url": url})
                continue

            if is_admin_path(url):
                log.debug("admin_path_skipped", extra={"url": url})
                continue

            if settings.skip_wp_archives and is_wp_noise_path(url):
                log.debug("wp_noise_skipped", extra={"url": url})
                continue

            if robots_data and not robots_data.is_allowed(url):
                log.info("robots_blocked", extra={"url": url})
                all_issues.append(make_issue("ROBOTS_BLOCKED", url))
                continue

            if len(all_pages) >= settings.max_pages:
                log.info("max_pages_reached", extra={"max": settings.max_pages})
                break

            # URL structure checks run before fetching (pure string operations)
            all_issues.extend(check_url_structure(url))

            await asyncio.sleep(crawl_delay_s)

            if on_progress:
                payload = {
                    "pages_crawled": len(all_pages),
                    "pages_total": pages_total,
                    "current_url": url,
                    "phase": "crawling_pages",
                    "external_links_checked": 0,
                    "external_links_total": 0,
                }
                result = on_progress(payload)
                if inspect.isawaitable(result):
                    await result

            try:
                result = await fetch_page(url, client)
            except Exception as exc:
                log.warning("fetch_exception", extra={"url": url, "error": str(exc)})
                continue

            log.info(
                "page_crawled",
                extra={"url": url, "status_code": result.status_code},
            )

            # Handle redirect loop
            if result.error == "REDIRECT_LOOP":
                all_issues.append(make_issue("REDIRECT_LOOP", url))
                continue

            # Handle fetch errors / timeouts (network failure, status_code=0)
            if result.error and result.status_code == 0:
                log.warning("fetch_failed", extra={"url": url, "error": result.error})
                # Emit a PAGE_TIMEOUT issue so the user knows the page was attempted
                timeout_issue = make_issue("PAGE_TIMEOUT", url)
                all_issues.append(timeout_issue)
                continue

            # Login redirect
            if result.is_login_redirect:
                all_issues.append(make_issue("LOGIN_REDIRECT", url))
                continue

            # Redirect issues
            if result.redirect_chain:
                redirect_issues = issues_for_redirect(
                    url, result.first_status_code, result.redirect_chain,
                    final_url=result.final_url,
                    base_url=normalised_start,
                )
                all_issues.extend(redirect_issues)
                # Add final URL to visited so we don't crawl it again
                try:
                    visited.add(normalise_url(result.final_url))
                except ValueError:
                    pass

            try:
                is_homepage = (url == normalised_start)
                page = parse_page(result, normalised_start, is_homepage=is_homepage)
            except Exception as exc:
                log.warning("parse_exception", extra={"url": url, "error": str(exc)})
                continue

            page.crawl_depth = current_depth
            all_pages.append(page)

            # ── Branch: HTML vs non-HTML assets ───────────────────────────
            ct = result.content_type
            is_html = "html" in ct
            is_asset = "pdf" in ct or ct.startswith("image/")

            print(f"[DEBUG] url={url}, ct={ct}, is_html={is_html}, has_image_data={page.image_data is not None}, image_count={len(page.image_data) if page.image_data else 0}")

            if is_html:
                # Skip SEO checks on 4xx/5xx pages — they are error pages, not real content.
                # Emit a BROKEN_LINK_404 (or 5xx variant) issue so the user knows this internal
                # page is broken.
                if result.status_code >= 400:
                    broken = issue_for_status(result.status_code, url)
                    page_issues = [broken] if broken else []
                else:
                    try:
                        page_issues = check_page(
                            page,
                            sitemap_urls=sitemap_url_set or None,
                            favicon_emitted=favicon_emitted,
                            hsts_checked_hosts=hsts_checked_hosts,
                            page_size_limit_kb=settings.page_size_limit_kb,
                            suppress_h1_strings=settings.suppress_h1_strings,
                            suppress_banner_h1=settings.suppress_banner_h1,
                            exempt_anchor_urls=settings.exempt_anchor_urls or None,
                        )
                    except Exception as exc:
                        log.warning("issue_check_exception", extra={"url": url, "error": str(exc)})
                        page_issues = []

                # Track favicon emission so we only emit once per job
                if any(i.code == "FAVICON_MISSING" for i in page_issues):
                    favicon_emitted = True

            elif is_asset:
                log.info("asset_crawled", extra={"url": url, "content_type": ct})
                page_issues = check_asset(result, img_size_limit_kb=settings.img_size_limit_kb)

            else:
                # Unknown binary (video, font, etc.) — record status only, no checks
                log.debug("binary_skipped", extra={"url": url, "content_type": ct})
                page_issues = []

            all_issues.extend(page_issues)

            # Queue new URLs from links (only HTML pages have links)
            child_depth = (current_depth + 1) if current_depth is not None else None
            for link in page.links:
                if link.is_internal:
                    try:
                        norm = normalise_url(link.url)
                    except ValueError:
                        continue
                    if norm not in visited:
                        # Only update depth_map if we haven't seen this URL yet
                        # (first discovery via HTML gives the shallowest depth)
                        if norm not in depth_map:
                            depth_map[norm] = child_depth
                        queue.append((norm, depth_map[norm]))
                else:
                    # Collect external links for later checking (subject to caps)
                    per_page = external_per_page_count.get(url, 0)
                    target = link.url
                    if per_page < _EXTERNAL_LINK_CAP_PER_PAGE and target not in external_targets_seen:
                        external_link_queue.append({
                            "source_url": url,
                            "target_url": target,
                            "link_text": link.text,
                        })
                        external_per_page_count[url] = per_page + 1
                        external_targets_seen.add(target)

            # Collect image data for full analysis (v1.9image)
            if is_html:
                img_count = len(page.image_data) if page.image_data else 0
                print(f"[IMG] Page {url} has {img_count} images, is_html={is_html}")
                if page.image_data:
                    for img_data in page.image_data:
                        img_url = img_data.get("url")
                        if img_url and img_url not in image_targets_seen and len(image_data_queue) < _IMAGE_URL_CAP_PER_JOB:
                            image_data_queue.append(img_data)
                            image_targets_seen.add(img_url)

        # ── 5. External link checking ─────────────────────────────────────
        external_checked = 0
        external_total = min(len(external_link_queue), _EXTERNAL_LINK_CAP_PER_JOB)
        # (target_url, source_url, link_text) for every broken external link.
        broken_link_sources: list[tuple[str, str, str | None]] = []

        # Update phase to external link checking
        if on_progress and external_total > 0:
            payload = {
                "pages_crawled": len(all_pages),
                "pages_total": pages_total,
                "current_url": None,
                "phase": "checking_external_links",
                "external_links_checked": 0,
                "external_links_total": external_total,
            }
            result = on_progress(payload)
            if inspect.isawaitable(result):
                await result

        for ext in external_link_queue:
            if cancel_event and cancel_event.is_set():
                break
            if external_checked >= _EXTERNAL_LINK_CAP_PER_JOB:
                log.info("external_link_cap_reached", extra={"cap": _EXTERNAL_LINK_CAP_PER_JOB})
                break

            target = ext["target_url"]
            if _is_bot_blocking_domain(target):
                # If the user has verified this URL, skip the notice entirely.
                if target not in settings.verified_link_urls:
                    # page_url = source page (internal), target_url in extra = external link
                    issue = make_issue("EXTERNAL_LINK_SKIPPED", ext["source_url"])
                    issue.extra = {"target_url": target}
                    issue.description = f"Link to {target} was skipped — the site may block bots"
                    all_issues.append(issue)
                external_checked += 1
                continue

            result = await _check_external_link(target, client)
            external_checked += 1

            # Update progress every 10 links or on last link
            if on_progress and (external_checked % 10 == 0 or external_checked == external_total):
                payload = {
                    "pages_crawled": len(all_pages),
                    "pages_total": pages_total,
                    "current_url": None,
                    "phase": "checking_external_links",
                    "external_links_checked": external_checked,
                    "external_links_total": external_total,
                }
                result_prog = on_progress(payload)
                if inspect.isawaitable(result_prog):
                    await result_prog

            if result is not None:
                source_url = ext["source_url"]
                if result.status_code == 0 and result.error:
                    # Timeout or connection failure — report as an info notice
                    # page_url = source page (internal), target_url in extra = broken link
                    issue = make_issue("EXTERNAL_LINK_TIMEOUT", source_url)
                    issue.extra = {"target_url": target}
                    issue.description = f"Link to {target} did not respond — destination may be slow or unavailable"
                    all_issues.append(issue)
                    broken_link_sources.append((target, source_url, ext.get("link_text")))
                else:
                    issue = issue_for_status(result.status_code, target)
                    if issue:
                        # page_url = source page (internal), target_url in extra = broken link
                        issue.page_url = source_url
                        issue.extra = {"target_url": target}
                        # Update description to include the broken URL
                        issue.description = f"Link to {target} returns {result.status_code}"
                        all_issues.append(issue)
                        broken_link_sources.append((target, source_url, ext.get("link_text")))

        # ── 5.5 Image analysis (v1.9image) ─────────────────────────────────
        # Collect image metadata from HTML without fetching actual images
        # Full image data (dimensions, size) fetched on-demand via API
        all_images: list[ImageInfo] = []

        print(f"[IMG] image_data_queue has {len(image_data_queue)} entries")

        try:
            image_config = {
                "max_image_size_kb": settings.img_size_limit_kb,
            }

            # Filter valid images
            valid_img_data = [d for d in image_data_queue if d.get("url")]
            print(f"[IMG] valid_img_data has {len(valid_img_data)} entries")

            if valid_img_data:
                log.info("collecting_images", extra={"count": len(valid_img_data)})

                # ═══════════════════════════════════════════════════════════════════
                # CRITICAL ARCHITECTURAL PRINCIPLE - DO NOT VIOLATE
                # ═══════════════════════════════════════════════════════════════════
                #
                # The SCAN process must ONLY use data from:
                # 1. HTML parsing (alt, title from <img> tags) - ALREADY DONE in parser.py
                # 2. HTTP HEAD requests (file size, content-type) - FAST, just headers
                #
                # The SCAN must NEVER call WordPress API because:
                # - WP API calls are SLOW (100 images = 100+ API requests)
                # - WP API only works on WordPress sites (HTML works on ANY site)
                # - This would make crawls unacceptably slow
                #
                # WordPress-specific data (caption, description, WP alt text) is
                # fetched ONLY via the manual "Fetch" button using slug-based queries.
                #
                # ═══════════════════════════════════════════════════════════════════

                # Do HEAD requests to get file size and content-type for ALL images
                # This is fast (just HTTP headers) and works on any site
                head_metadata_cache: dict[str, dict] = {}
                if valid_img_data:
                    async def fetch_head_meta(img_url: str):
                        try:
                            response = await client.head(img_url, timeout=3.0, follow_redirects=True)
                            if response.status_code == 200:
                                content_length = response.headers.get("content-length")
                                content_type = response.headers.get("content-type", "")
                                return (img_url, {
                                    "file_size": int(content_length) if content_length else None,
                                    "content_type": content_type,
                                })
                        except Exception:
                            pass
                        return (img_url, {})

                    try:
                        head_tasks = [fetch_head_meta(d["url"]) for d in valid_img_data]
                        if head_tasks:
                            head_results = await asyncio.wait_for(
                                asyncio.gather(*head_tasks, return_exceptions=True),
                                timeout=10.0
                            )
                            for item in head_results:
                                if isinstance(item, tuple) and item[1]:
                                    head_metadata_cache[item[0]] = item[1]
                            print(f"[IMG] Got HEAD metadata for {len(head_metadata_cache)} images")
                    except Exception as head_exc:
                        print(f"[IMG] HEAD metadata fetch failed: {head_exc}")

                for img_data in valid_img_data:
                    img_url = img_data["url"]
                    head_meta = head_metadata_cache.get(img_url, {})

                    # Get file size and content-type from HEAD request
                    # Width/height are NOT available from HEAD - will be fetched on-demand via "Fetch" button
                    width = None
                    height = None
                    file_size = head_meta.get("file_size")
                    mime_type = head_meta.get("content_type")
                    fmt = _guess_format_from_url(img_url)
                    if mime_type:
                        # Extract format from mime_type like "image/jpeg"
                        fmt = mime_type.split("/")[-1] if "/" in mime_type else fmt

                    # Data source is always "html_only" during scan
                    # Scan gets: alt/title from HTML + file size from HEAD request
                    # Full metadata (caption, description, WP fields) requires manual "Fetch"
                    data_source = "html_only"

                    image_info = ImageInfo(
                        url=img_url,
                        page_url=img_data.get("page_url", ""),
                        job_id=job_id,
                        alt=img_data.get("alt"),
                        title=img_data.get("title"),
                        filename=_extract_filename(img_url),
                        format=fmt,
                        width=width,
                        height=height,
                        rendered_width=img_data.get("rendered_width"),
                        rendered_height=img_data.get("rendered_height"),
                        file_size_bytes=file_size,
                        load_time_ms=None,
                        http_status=0,  # Only set when image is actually fetched via "Get Details"
                        is_lazy_loaded=img_data.get("is_lazy_loaded", False),
                        has_srcset=img_data.get("has_srcset", False),
                        srcset_candidates=img_data.get("srcset_candidates", []),
                        is_decorative=img_data.get("is_decorative", False),
                        surrounding_text=img_data.get("surrounding_text", ""),
                        content_hash=None,
                        data_source=data_source,
                    )
                    all_images.append(image_info)

            # Run batch analysis on HTML-level data (alt text checks work without fetch)
            if all_images:
                # Update phase to analyzing images
                if on_progress:
                    payload = {
                        "pages_crawled": len(all_pages),
                        "pages_total": pages_total,
                        "current_url": None,
                        "phase": "analyzing_images",
                        "external_links_checked": external_checked,
                        "external_links_total": external_total,
                    }
                    result_prog = on_progress(payload)
                    if inspect.isawaitable(result_prog):
                        await result_prog

                analyzed_images, image_issues = analyze_images(
                    all_images,
                    config=image_config,
                    job_id=job_id,
                )
                all_images = analyzed_images
                all_issues.extend(image_issues)

                log.info("images_analyzed", extra={
                    "total": len(all_images),
                    "issues_found": len(image_issues),
                })

        except Exception as img_exc:
            print(f"[IMG] Exception during image analysis: {img_exc}")
            log.exception("image_analysis_failed", extra={"error": str(img_exc)})
            all_images = []  # Continue crawl without images

        print(f"[IMG] Final all_images count: {len(all_images)}")

        # ── 6. AMP HTML link checking ────────────────────────────────────
        amp_statuses: dict[str, int] = {}
        seen_amp_urls: set[str] = set()
        for p in all_pages:
            if p.amphtml_url and p.amphtml_url not in seen_amp_urls:
                seen_amp_urls.add(p.amphtml_url)
                try:
                    amp_result = await _check_external_link(p.amphtml_url, client)
                    if amp_result is not None:
                        amp_statuses[p.amphtml_url] = amp_result.status_code
                except Exception:
                    pass
        amp_issues = check_amphtml_links(all_pages, amp_statuses)
        all_issues.extend(amp_issues)

        # ── 7. Cross-page duplicate checks (HTML pages only) ─────────────
        html_pages = [p for p in all_pages if p.title is not None or p.meta_description is not None or p.h1_tags]
        cross_issues = check_cross_page(html_pages, start_url=normalised_start)
        all_issues.extend(cross_issues)

        # ── 8. Apply analysis-toggle category filter ──────────────────────
        allowed = _enabled_categories(settings.enabled_analyses)
        if allowed is not None:
            all_issues = [i for i in all_issues if i.category in allowed]

        log.info(
            "crawl_complete",
            extra={
                "pages_crawled": len(all_pages),
                "issues_found": len(all_issues),
                "external_links_checked": external_checked,
            },
        )

        # Update phase to complete
        if on_progress:
            payload = {
                "pages_crawled": len(all_pages),
                "pages_total": pages_total,
                "current_url": None,
                "phase": "complete",
                "external_links_checked": external_checked,
                "external_links_total": external_total,
            }
            result_prog = on_progress(payload)
            if inspect.isawaitable(result_prog):
                await result_prog

        return CrawlResult(
            job_id=job_id,
            pages=all_pages,
            issues=all_issues,
            pages_crawled=len(all_pages),
            external_links_checked=external_checked,
            broken_link_sources=broken_link_sources,
            images=all_images,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_bot_blocking_domain(url: str) -> bool:
    """Return True if *url* belongs to a domain known to block automated requests."""
    host = urlparse(url).hostname or ""
    return host in _BOT_BLOCKING_DOMAINS


async def _check_external_link(
    url: str, client: httpx.AsyncClient
) -> FetchResult | None:
    """Issue a HEAD request for *url*, falling back to GET on 405."""
    result = await fetch_page(url, client, is_head=True)
    if result.status_code == 405:
        result = await fetch_page(url, client, is_head=False)
    return result


async def _fetch_image_full(
    url: str,
    client: httpx.AsyncClient,
    timeout: float = 3.0,
    max_size: int = 5 * 1024 * 1024,  # 5MB
) -> dict:
    """Fetch full image data including bytes for dimension extraction.

    Returns a dict with:
    - http_status: int
    - file_size_bytes: int|None
    - load_time_ms: int|None
    - width: int|None (intrinsic)
    - height: int|None (intrinsic)
    - format: str
    - content_hash: str|None (MD5)
    - error: str|None
    """
    import hashlib
    import time

    start_time = time.time()
    result = {
        "url": url,
        "http_status": 0,
        "file_size_bytes": None,
        "load_time_ms": None,
        "width": None,
        "height": None,
        "format": "unknown",
        "content_hash": None,
        "error": None,
    }

    try:
        response = await client.get(url, timeout=timeout)
        result["http_status"] = response.status_code
        result["load_time_ms"] = int((time.time() - start_time) * 1000)

        if response.status_code < 400:
            content = response.content
            result["file_size_bytes"] = len(content)

            # Hash for duplicate detection
            result["content_hash"] = hashlib.md5(content).hexdigest()

            # Extract dimensions using Pillow
            try:
                from PIL import Image
                import io
                img = Image.open(io.BytesIO(content))
                result["width"], result["height"] = img.size
                result["format"] = img.format.lower() if img.format else "unknown"
            except Exception:
                pass

    except Exception as e:
        result["error"] = str(e)
        result["load_time_ms"] = int((time.time() - start_time) * 1000)

    return result


def _extract_filename(url: str) -> str:
    """Extract filename from URL path."""
    try:
        path = urlparse(url).path
        if path:
            return path.rstrip("/").rsplit("/", 1)[-1]
    except Exception:
        pass
    return ""


def _guess_format_from_url(url: str) -> str:
    """Guess image format from URL extension."""
    try:
        path = urlparse(url).path.lower()
        if path.endswith(".webp"):
            return "webp"
        elif path.endswith(".avif"):
            return "avif"
        elif path.endswith((".jpg", ".jpeg")):
            return "jpeg"
        elif path.endswith(".png"):
            return "png"
        elif path.endswith(".gif"):
            return "gif"
        elif path.endswith(".svg"):
            return "svg"
        elif path.endswith(".ico"):
            return "ico"
    except Exception:
        pass
    return "unknown"


async def _get_wp_image_metadata(
    image_url: str,
    client: httpx.AsyncClient,
    wp_api_base: str | None = None,
) -> dict | None:
    """Try to get image metadata from WordPress REST API.

    Returns dict with width, height, filesize, mime_type if found, else None.
    """
    if not wp_api_base:
        # Derive from image URL - assume /wp-content/uploads/ pattern
        parsed = urlparse(image_url)
        if "/wp-content/uploads/" not in parsed.path:
            return None
        wp_api_base = f"{parsed.scheme}://{parsed.netloc}/wp-json/wp/v2"

    # Extract filename from URL for search
    filename = image_url.rsplit("/", 1)[-1] if "/" in image_url else ""
    if not filename:
        return None

    # Remove size suffix like -300x200 before extension
    import re
    base_filename = re.sub(r'-\d+x\d+(\.[a-z]+)$', r'\1', filename, flags=re.IGNORECASE)
    search_term = base_filename.rsplit(".", 1)[0] if "." in base_filename else base_filename

    try:
        # Search WordPress media library
        search_url = f"{wp_api_base}/media?search={search_term}&per_page=5"
        response = await client.get(search_url, timeout=5.0)

        if response.status_code != 200:
            return None

        media_items = response.json()
        if not media_items or not isinstance(media_items, list):
            return None

        # Find matching image by URL
        for item in media_items:
            source_url = item.get("source_url", "")
            # Check if this is our image (match base filename)
            if base_filename in source_url or filename in source_url:
                details = item.get("media_details", {})
                return {
                    "width": details.get("width"),
                    "height": details.get("height"),
                    "filesize": details.get("filesize"),
                    "mime_type": item.get("mime_type"),
                    "alt_text": item.get("alt_text"),
                    "wp_id": item.get("id"),
                }

        # If no exact match, return first result if filename is similar
        if media_items:
            item = media_items[0]
            details = item.get("media_details", {})
            return {
                "width": details.get("width"),
                "height": details.get("height"),
                "filesize": details.get("filesize"),
                "mime_type": item.get("mime_type"),
                "alt_text": item.get("alt_text"),
                "wp_id": item.get("id"),
            }

    except Exception:
        pass

    return None


def _effective_delay(base_delay_s: float, robots_data: RobotsData | None) -> float:
    """Return the effective crawl delay, respecting robots.txt and the minimum."""
    min_s = _MIN_CRAWL_DELAY_MS / 1000.0
    if robots_data and robots_data.crawl_delay is not None:
        return max(min_s, robots_data.crawl_delay, base_delay_s)
    return max(min_s, base_delay_s)


