"""
Async crawl engine for the TalkingToad crawler.

Orchestrates the full crawl: URL queue management, robots.txt enforcement,
crawl delay, external link checking, and issue aggregation (spec §2.4, §2.8).
"""

import asyncio
import inspect
import logging
import os
from collections import deque
from dataclasses import dataclass, field
from typing import Callable
from urllib.parse import urlparse

import httpx

from api.crawler.fetcher import FetchResult, fetch_page, make_client
from api.crawler.issue_checker import (
    Issue,
    check_amphtml_links,
    check_asset,
    check_cross_page,
    check_page,
    check_url_structure,
    issue_for_status,
    issues_for_redirect,
    make_issue,
)
from api.crawler.normaliser import (
    QueryVariantTracker,
    is_admin_path,
    is_same_domain,
    is_wp_noise_path,
    normalise_url,
)
from api.crawler.parser import ParsedPage, parse_page
from api.crawler.robots import RobotsData, fetch_robots
from api.crawler.sitemap import fetch_sitemap_recursive

logger = logging.getLogger(__name__)

_DEFAULT_MAX_PAGES = int(os.getenv("MAX_PAGES_PER_CRAWL", "500"))
_MIN_CRAWL_DELAY_MS = 200
_EXTERNAL_LINK_CAP_PER_PAGE = 50
_EXTERNAL_LINK_CAP_PER_JOB = 500

# Social media and other platforms known to block automated HTTP requests.
# Checking these produces false positives (e.g. LinkedIn returns 999, Facebook
# redirects to a login wall). We skip external link checking for these domains
# entirely — a human click will work fine even though a bot request fails.
_BOT_BLOCKING_DOMAINS: frozenset[str] = frozenset(
    [
        "linkedin.com",
        "www.linkedin.com",
        "facebook.com",
        "www.facebook.com",
        "fb.com",
        "instagram.com",
        "www.instagram.com",
        "twitter.com",
        "www.twitter.com",
        "x.com",
        "www.x.com",
        "tiktok.com",
        "www.tiktok.com",
    ]
)


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

# Maps analysis toggle names (v1.3 §3.1) to the issue categories they cover.
_ANALYSIS_CATEGORY_MAP: dict[str, frozenset[str]] = {
    "link_integrity": frozenset({"broken_link", "redirect"}),
    "seo_essentials": frozenset({"metadata", "duplicate", "url_structure"}),
    "site_structure": frozenset({"heading"}),
    "indexability":   frozenset({"crawlability", "sitemap"}),
}
# Categories not covered by a named group are always emitted (security).
_UNGROUPED_CATEGORIES: frozenset[str] = frozenset({"security"})


def _enabled_categories(enabled_analyses: list[str] | None) -> frozenset[str] | None:
    """Return the set of allowed issue categories, or None if all are enabled."""
    if enabled_analyses is None:
        return None
    cats: set[str] = set(_UNGROUPED_CATEGORIES)
    for group in enabled_analyses:
        cats.update(_ANALYSIS_CATEGORY_MAP.get(group, frozenset()))
    return frozenset(cats)


@dataclass
class CrawlSettings:
    max_pages: int = _DEFAULT_MAX_PAGES
    crawl_delay_ms: int = 500
    respect_robots: bool = True
    include_subdomains: list[str] = field(default_factory=list)
    # None = all analyses enabled; supply a list of group names to restrict.
    enabled_analyses: list[str] | None = None
    # Image size threshold in KB — images larger than this are flagged as IMG_OVERSIZED.
    img_size_limit_kb: int = 200
    # Page HTML size threshold in KB — pages larger than this are flagged as PAGE_SIZE_LARGE.
    page_size_limit_kb: int = 300
    # Skip WordPress author/category/tag archive pages (default True).
    # These pages are auto-generated by WP and produce non-actionable issues.
    skip_wp_archives: bool = True


@dataclass
class CrawlResult:
    job_id: str
    pages: list[ParsedPage]
    issues: list[Issue]
    pages_crawled: int
    external_links_checked: int
    cancelled: bool = False


# ---------------------------------------------------------------------------
# Engine entry point
# ---------------------------------------------------------------------------

ProgressCallback = Callable[[dict], None]


async def run_crawl(
    job_id: str,
    target_url: str,
    settings: CrawlSettings | None = None,
    *,
    on_progress: ProgressCallback | None = None,
    cancel_event: asyncio.Event | None = None,
) -> CrawlResult:
    """Run a full crawl of *target_url* and return a :class:`CrawlResult`.

    Args:
        job_id: Unique identifier for this crawl job (used in log entries).
        target_url: The start URL to crawl (must include scheme).
        settings: Crawl configuration. Falls back to defaults if None.
        on_progress: Optional callback invoked after each page is crawled.
            Receives a dict with ``pages_crawled``, ``pages_total``, ``current_url``.
        cancel_event: If set, the engine checks this after each page and stops
            cleanly when the event fires.
    """
    if settings is None:
        settings = CrawlSettings()

    crawl_delay_s = max(_MIN_CRAWL_DELAY_MS, settings.crawl_delay_ms) / 1000.0

    try:
        normalised_start = normalise_url(target_url)
    except ValueError:
        logger.error("invalid_target_url", extra={"job_id": job_id, "url": target_url})
        return CrawlResult(job_id=job_id, pages=[], issues=[], pages_crawled=0, external_links_checked=0)

    log = logging.LoggerAdapter(logger, {"job_id": job_id})

    async with make_client() as client:
        # ── 1. Fetch robots.txt ────────────────────────────────────────────
        robots_data: RobotsData | None = None
        if settings.respect_robots:
            robots_data = await fetch_robots(normalised_start, client)
            crawl_delay_s = _effective_delay(crawl_delay_s, robots_data)

        # ── 2. Fetch sitemap ──────────────────────────────────────────────
        robots_sitemap_urls = robots_data.sitemap_urls if robots_data else []
        sitemap_result = await fetch_sitemap_recursive(
            normalised_start, client, robots_sitemap_urls=robots_sitemap_urls
        )

        sitemap_url_set: set[str] = set(sitemap_result.urls)
        pages_total: int | None = len(sitemap_url_set) if sitemap_url_set else None

        all_pages: list[ParsedPage] = []
        all_issues: list[Issue] = []
        favicon_emitted = False
        hsts_checked_hosts: set[str] = set()

        # ── 2.5. HTTPS redirect check ─────────────────────────────────────
        # If the site is HTTPS, verify that the HTTP version redirects to HTTPS.
        if normalised_start.startswith("https://"):
            http_url = "http://" + normalised_start[8:]
            try:
                http_result = await fetch_page(http_url, client)
                redirects_to_https = (
                    http_result.final_url is not None
                    and http_result.final_url.startswith("https://")
                )
                if not redirects_to_https:
                    all_issues.append(make_issue("HTTPS_REDIRECT_MISSING", normalised_start))
            except Exception:
                pass  # network error — cannot determine redirect behaviour

        # If no sitemap found, record that as an issue
        if sitemap_result.missing_issue:
            all_issues.append(
                Issue(
                    code="SITEMAP_MISSING",
                    category="sitemap",
                    severity="info",
                    description=sitemap_result.missing_issue["message"],
                    recommendation="Create an XML sitemap and submit it to Google Search Console. Most CMS platforms can generate one automatically.",
                    page_url=None,
                )
            )

        # ── 3. Crawl queue setup ──────────────────────────────────────────
        # Queue entries are (url, depth); homepage depth = 0, sitemap-seeded = None
        queue: deque[tuple[str, int | None]] = deque([(normalised_start, 0)])
        visited: set[str] = set()
        variant_tracker = QueryVariantTracker()
        depth_map: dict[str, int | None] = {normalised_start: 0}

        # Seed from sitemap so pages not reachable via HTML links are crawled
        for su in sitemap_result.urls:
            try:
                norm = normalise_url(su)
            except ValueError:
                continue
            if norm != normalised_start and is_same_domain(norm, normalised_start):
                queue.append((norm, None))
                if norm not in depth_map:
                    depth_map[norm] = None

        # External links: collected during internal crawl, checked after
        # Format: {"source_url": str, "target_url": str, "link_text": str|None}
        external_link_queue: list[dict] = []
        external_per_page_count: dict[str, int] = {}
        external_targets_seen: set[str] = set()  # deduplicate by target URL

        # Image URLs: collected during internal crawl, checked after for broken images
        # Format: {"page_url": str, "image_url": str}
        _IMAGE_URL_CAP_PER_JOB = 200
        image_url_queue: list[dict] = []
        image_targets_seen: set[str] = set()

        # ── 4. Internal crawl loop ────────────────────────────────────────
        while queue:
            if cancel_event and cancel_event.is_set():
                log.info("crawl_cancelled")
                return CrawlResult(
                    job_id=job_id,
                    pages=all_pages,
                    issues=all_issues,
                    pages_crawled=len(all_pages),
                    external_links_checked=0,
                    cancelled=True,
                )

            url, current_depth = queue.popleft()

            if url in visited:
                continue
            visited.add(url)

            if not variant_tracker.record(url):
                log.warning("query_variant_cap_reached", extra={"url": url})
                continue

            if is_admin_path(url):
                log.debug("admin_path_skipped", extra={"url": url})
                continue

            if settings.skip_wp_archives and is_wp_noise_path(url):
                log.debug("wp_noise_skipped", extra={"url": url})
                continue

            if robots_data and not robots_data.is_allowed(url):
                log.info("robots_blocked", extra={"url": url})
                all_issues.append(make_issue("ROBOTS_BLOCKED", url))
                continue

            if len(all_pages) >= settings.max_pages:
                log.info("max_pages_reached", extra={"max": settings.max_pages})
                break

            # URL structure checks run before fetching (pure string operations)
            all_issues.extend(check_url_structure(url))

            await asyncio.sleep(crawl_delay_s)

            if on_progress:
                payload = {
                    "pages_crawled": len(all_pages),
                    "pages_total": pages_total,
                    "current_url": url,
                }
                result = on_progress(payload)
                if inspect.isawaitable(result):
                    await result

            try:
                result = await fetch_page(url, client)
            except Exception as exc:
                log.warning("fetch_exception", extra={"url": url, "error": str(exc)})
                continue

            log.info(
                "page_crawled",
                extra={"url": url, "status_code": result.status_code},
            )

            # Handle redirect loop
            if result.error == "REDIRECT_LOOP":
                all_issues.append(make_issue("REDIRECT_LOOP", url))
                continue

            # Handle fetch errors / timeouts (network failure, status_code=0)
            if result.error and result.status_code == 0:
                log.warning("fetch_failed", extra={"url": url, "error": result.error})
                # Emit a PAGE_TIMEOUT issue so the user knows the page was attempted
                timeout_issue = make_issue("PAGE_TIMEOUT", url)
                all_issues.append(timeout_issue)
                continue

            # Login redirect
            if result.is_login_redirect:
                all_issues.append(make_issue("LOGIN_REDIRECT", url))
                continue

            # Redirect issues
            if result.redirect_chain:
                redirect_issues = issues_for_redirect(
                    url, result.first_status_code, result.redirect_chain,
                    final_url=result.final_url,
                    base_url=normalised_start,
                )
                all_issues.extend(redirect_issues)
                # Add final URL to visited so we don't crawl it again
                try:
                    visited.add(normalise_url(result.final_url))
                except ValueError:
                    pass

            try:
                is_homepage = (url == normalised_start)
                page = parse_page(result, normalised_start, is_homepage=is_homepage)
            except Exception as exc:
                log.warning("parse_exception", extra={"url": url, "error": str(exc)})
                continue

            page.crawl_depth = current_depth
            all_pages.append(page)

            # ── Branch: HTML vs non-HTML assets ───────────────────────────
            ct = result.content_type
            is_html = "html" in ct
            is_asset = "pdf" in ct or ct.startswith("image/")

            if is_html:
                # Skip SEO checks on 4xx/5xx pages — they are error pages, not real content.
                # Emit a BROKEN_LINK_404 (or 5xx variant) issue so the user knows this internal
                # page is broken.
                if result.status_code >= 400:
                    broken = issue_for_status(result.status_code, url)
                    page_issues = [broken] if broken else []
                else:
                    try:
                        page_issues = check_page(
                            page,
                            sitemap_urls=sitemap_url_set or None,
                            favicon_emitted=favicon_emitted,
                            hsts_checked_hosts=hsts_checked_hosts,
                            page_size_limit_kb=settings.page_size_limit_kb,
                        )
                    except Exception as exc:
                        log.warning("issue_check_exception", extra={"url": url, "error": str(exc)})
                        page_issues = []

                # Track favicon emission so we only emit once per job
                if any(i.code == "FAVICON_MISSING" for i in page_issues):
                    favicon_emitted = True

            elif is_asset:
                log.info("asset_crawled", extra={"url": url, "content_type": ct})
                page_issues = check_asset(result, img_size_limit_kb=settings.img_size_limit_kb)

            else:
                # Unknown binary (video, font, etc.) — record status only, no checks
                log.debug("binary_skipped", extra={"url": url, "content_type": ct})
                page_issues = []

            all_issues.extend(page_issues)

            # Queue new URLs from links (only HTML pages have links)
            child_depth = (current_depth + 1) if current_depth is not None else None
            for link in page.links:
                if link.is_internal:
                    try:
                        norm = normalise_url(link.url)
                    except ValueError:
                        continue
                    if norm not in visited:
                        # Only update depth_map if we haven't seen this URL yet
                        # (first discovery via HTML gives the shallowest depth)
                        if norm not in depth_map:
                            depth_map[norm] = child_depth
                        queue.append((norm, depth_map[norm]))
                else:
                    # Collect external links for later checking (subject to caps)
                    per_page = external_per_page_count.get(url, 0)
                    target = link.url
                    if per_page < _EXTERNAL_LINK_CAP_PER_PAGE and target not in external_targets_seen:
                        external_link_queue.append({
                            "source_url": url,
                            "target_url": target,
                            "link_text": link.text,
                        })
                        external_per_page_count[url] = per_page + 1
                        external_targets_seen.add(target)

            # Collect image URLs for broken-image checking
            if is_html and page.image_urls:
                for img_url in page.image_urls:
                    if img_url not in image_targets_seen and len(image_url_queue) < _IMAGE_URL_CAP_PER_JOB:
                        image_url_queue.append({"page_url": url, "image_url": img_url})
                        image_targets_seen.add(img_url)

        # ── 5. External link checking ─────────────────────────────────────
        external_checked = 0
        for ext in external_link_queue:
            if cancel_event and cancel_event.is_set():
                break
            if external_checked >= _EXTERNAL_LINK_CAP_PER_JOB:
                log.info("external_link_cap_reached", extra={"cap": _EXTERNAL_LINK_CAP_PER_JOB})
                break

            target = ext["target_url"]
            if _is_bot_blocking_domain(target):
                # Emit an info-level notice so the user can verify manually.
                issue = make_issue("EXTERNAL_LINK_SKIPPED", target)
                issue.extra = {"source_url": ext["source_url"]}
                all_issues.append(issue)
                external_checked += 1
                continue

            result = await _check_external_link(target, client)
            external_checked += 1

            if result is not None:
                if result.status_code == 0 and result.error:
                    # Timeout or connection failure — report as an info notice
                    issue = make_issue("EXTERNAL_LINK_TIMEOUT", target)
                    issue.extra = {"source_url": ext["source_url"]}
                    all_issues.append(issue)
                else:
                    issue = issue_for_status(result.status_code, target)
                    if issue:
                        issue.extra = {"source_url": ext["source_url"]}
                        all_issues.append(issue)

        # ── 5.5 Broken image checking ─────────────────────────────────────
        for img in image_url_queue:
            if cancel_event and cancel_event.is_set():
                break
            img_result = await _check_external_link(img["image_url"], client)
            if img_result is not None and img_result.status_code >= 400:
                issue = make_issue(
                    "IMG_BROKEN", img["page_url"],
                    extra={"image_url": img["image_url"], "status_code": img_result.status_code},
                )
                all_issues.append(issue)

        # ── 6. AMP HTML link checking ────────────────────────────────────
        amp_statuses: dict[str, int] = {}
        seen_amp_urls: set[str] = set()
        for p in all_pages:
            if p.amphtml_url and p.amphtml_url not in seen_amp_urls:
                seen_amp_urls.add(p.amphtml_url)
                try:
                    amp_result = await _check_external_link(p.amphtml_url, client)
                    if amp_result is not None:
                        amp_statuses[p.amphtml_url] = amp_result.status_code
                except Exception:
                    pass
        amp_issues = check_amphtml_links(all_pages, amp_statuses)
        all_issues.extend(amp_issues)

        # ── 7. Cross-page duplicate checks (HTML pages only) ─────────────
        html_pages = [p for p in all_pages if p.title is not None or p.meta_description is not None or p.h1_tags]
        cross_issues = check_cross_page(html_pages, start_url=normalised_start)
        all_issues.extend(cross_issues)

        # ── 8. Apply analysis-toggle category filter ──────────────────────
        allowed = _enabled_categories(settings.enabled_analyses)
        if allowed is not None:
            all_issues = [i for i in all_issues if i.category in allowed]

        log.info(
            "crawl_complete",
            extra={
                "pages_crawled": len(all_pages),
                "issues_found": len(all_issues),
                "external_links_checked": external_checked,
            },
        )

        return CrawlResult(
            job_id=job_id,
            pages=all_pages,
            issues=all_issues,
            pages_crawled=len(all_pages),
            external_links_checked=external_checked,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _is_bot_blocking_domain(url: str) -> bool:
    """Return True if *url* belongs to a domain known to block automated requests."""
    host = urlparse(url).hostname or ""
    return host in _BOT_BLOCKING_DOMAINS


async def _check_external_link(
    url: str, client: httpx.AsyncClient
) -> FetchResult | None:
    """Issue a HEAD request for *url*, falling back to GET on 405."""
    result = await fetch_page(url, client, is_head=True)
    if result.status_code == 405:
        result = await fetch_page(url, client, is_head=False)
    return result


def _effective_delay(base_delay_s: float, robots_data: RobotsData | None) -> float:
    """Return the effective crawl delay, respecting robots.txt and the minimum."""
    min_s = _MIN_CRAWL_DELAY_MS / 1000.0
    if robots_data and robots_data.crawl_delay is not None:
        return max(min_s, robots_data.crawl_delay, base_delay_s)
    return max(min_s, base_delay_s)


